-- 01_create_typed_and_insert.sql
-- Create typed table with safer VARCHAR widths
DROP TABLE IF EXISTS public.diabetic;
CREATE TABLE public.diabetic (
  encounter_id             BIGINT PRIMARY KEY,
  patient_nbr              BIGINT,
  race                     VARCHAR(32),
  gender                   VARCHAR(20),
  age                      VARCHAR(16),
  weight                   VARCHAR(24),
  admission_type_id        INT,
  discharge_disposition_id INT,
  admission_source_id      INT,
  time_in_hospital         INT,
  payer_code               VARCHAR(20),
  medical_specialty        VARCHAR(100),
  num_lab_procedures       INT,
  num_procedures           INT,
  num_medications          INT,
  number_outpatient        INT,
  number_emergency         INT,
  number_inpatient         INT,
  diag_1                   VARCHAR(16),
  diag_2                   VARCHAR(16),
  diag_3                   VARCHAR(16),
  number_diagnoses         INT,
  max_glu_serum            VARCHAR(16),
  A1Cresult                VARCHAR(16),
  metformin                VARCHAR(12),
  repaglinide              VARCHAR(12),
  nateglinide              VARCHAR(12),
  chlorpropamide           VARCHAR(12),
  glimepiride              VARCHAR(12),
  acetohexamide            VARCHAR(12),
  glipizide                VARCHAR(12),
  glyburide                VARCHAR(12),
  tolbutamide              VARCHAR(12),
  pioglitazone             VARCHAR(12),
  rosiglitazone            VARCHAR(12),
  acarbose                 VARCHAR(12),
  miglitol                 VARCHAR(12),
  troglitazone             VARCHAR(12),
  tolazamide               VARCHAR(12),
  examide                  VARCHAR(12),
  citoglipton              VARCHAR(12),
  insulin                  VARCHAR(12),
  "glyburide-metformin"    VARCHAR(16),
  "glipizide-metformin"    VARCHAR(16),
  "glimepiride-pioglitazone" VARCHAR(24),
  "metformin-rosiglitazone"  VARCHAR(24),
  "metformin-pioglitazone"   VARCHAR(24),
  change                   VARCHAR(8),
  diabetesMed              VARCHAR(8),
  readmitted               VARCHAR(12)
);

-- Insert + clean from staging
INSERT INTO public.diabetic (
  encounter_id, patient_nbr, race, gender, age, weight,
  admission_type_id, discharge_disposition_id, admission_source_id,
  time_in_hospital, payer_code, medical_specialty,
  num_lab_procedures, num_procedures, num_medications,
  number_outpatient, number_emergency, number_inpatient,
  diag_1, diag_2, diag_3, number_diagnoses,
  max_glu_serum, A1Cresult,
  metformin, repaglinide, nateglinide, chlorpropamide, glimepiride, acetohexamide,
  glipizide, glyburide, tolbutamide, pioglitazone, rosiglitazone, acarbose,
  miglitol, troglitazone, tolazamide, examide, citoglipton,
  insulin, "glyburide-metformin", "glipizide-metformin",
  "glimepiride-pioglitazone", "metformin-rosiglitazone", "metformin-pioglitazone",
  change, diabetesMed, readmitted
)
SELECT
  encounter_id::BIGINT,
  patient_nbr::BIGINT,
  NULLIF(race, '?'),
  NULLIF(gender, '?'),
  NULLIF(age, '?'),
  NULLIF(weight, '?'),
  NULLIF(admission_type_id, '?')::INT,
  NULLIF(discharge_disposition_id, '?')::INT,
  NULLIF(admission_source_id, '?')::INT,
  NULLIF(time_in_hospital, '?')::INT,
  NULLIF(payer_code, '?'),
  NULLIF(medical_specialty, '?'),
  NULLIF(num_lab_procedures, '?')::INT,
  NULLIF(num_procedures, '?')::INT,
  NULLIF(num_medications, '?')::INT,
  NULLIF(number_outpatient, '?')::INT,
  NULLIF(number_emergency, '?')::INT,
  NULLIF(number_inpatient, '?')::INT,
  CASE WHEN diag_1 IN ('?','999') THEN NULL ELSE diag_1 END,
  CASE WHEN diag_2 IN ('?','999') THEN NULL ELSE diag_2 END,
  CASE WHEN diag_3 IN ('?','999') THEN NULL ELSE diag_3 END,
  NULLIF(number_diagnoses, '?')::INT,
  NULLIF(max_glu_serum, '?'),
  NULLIF(A1Cresult, '?'),
  NULLIF(metformin, '?'),
  NULLIF(repaglinide, '?'),
  NULLIF(nateglinide, '?'),
  NULLIF(chlorpropamide, '?'),
  NULLIF(glimepiride, '?'),
  NULLIF(acetohexamide, '?'),
  NULLIF(glipizide, '?'),
  NULLIF(glyburide, '?'),
  NULLIF(tolbutamide, '?'),
  NULLIF(pioglitazone, '?'),
  NULLIF(rosiglitazone, '?'),
  NULLIF(acarbose, '?'),
  NULLIF(miglitol, '?'),
  NULLIF(troglitazone, '?'),
  NULLIF(tolazamide, '?'),
  NULLIF(examide, '?'),
  NULLIF(citoglipton, '?'),
  NULLIF(insulin, '?'),
  NULLIF("glyburide-metformin", '?'),
  NULLIF("glipizide-metformin", '?'),
  NULLIF("glimepiride-pioglitazone", '?'),
  NULLIF("metformin-rosiglitazone", '?'),
  NULLIF("metformin-pioglitazone", '?'),
  NULLIF(change, '?'),
  NULLIF(diabetesMed, '?'),
  NULLIF(readmitted, '?')
FROM public.diabetic_stg;
